"""Add provider_id to SupportTicket

Revision ID: 8248923e7c12
Revises: f1_service_emergency_eligible
Create Date: 2026-09-09 10:31:34.685151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8248923e7c12'
down_revision: Union[str, Sequence[str], None] = 'f1_service_emergency_eligible'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_roles_user_id'), 'admin_roles', ['user_id'], unique=False)
    op.drop_constraint(op.f('admin_roles_user_id_fkey'), 'admin_roles', type_='foreignkey')
    op.create_foreign_key(None, 'admin_roles', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_risk_level'), 'audit_logs', ['risk_level'], unique=False)
    op.drop_constraint(op.f('audit_logs_actor_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'])
    op.alter_column('bookings', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.alter_column('certificates', 'expiry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('customers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_unique_constraint(None, 'customers', ['email'])
    op.create_index(op.f('ix_failed_login_attempts_email'), 'failed_login_attempts', ['email'], unique=False)
    op.alter_column('feedback', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_feedback_customer_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_provider_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_service_id'), table_name='feedback')
    op.drop_constraint(op.f('feedback_provider_id_fkey'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('feedback_service_id_fkey'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'providers', ['provider_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedback', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.add_column('support_tickets', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.alter_column('support_tickets', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_support_tickets_customer_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.create_foreign_key(None, 'support_tickets', 'providers', ['provider_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_customer_id'), 'support_tickets', ['customer_id'], unique=False)
    op.alter_column('support_tickets', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('support_tickets', 'provider_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_service_id_fkey'), 'feedback', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('feedback_provider_id_fkey'), 'feedback', 'providers', ['provider_id'], ['user_id'], ondelete='SET NULL')
    op.create_index(op.f('ix_feedback_service_id'), 'feedback', ['service_id'], unique=False)
    op.create_index(op.f('ix_feedback_provider_id'), 'feedback', ['provider_id'], unique=False)
    op.create_index(op.f('ix_feedback_customer_id'), 'feedback', ['customer_id'], unique=False)
    op.alter_column('feedback', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_failed_login_attempts_email'), table_name='failed_login_attempts')
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.alter_column('customers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('certificates', 'expiry_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_provider_id'), 'bookings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.alter_column('bookings', 'total_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_actor_id_fkey'), 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_risk_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_constraint(None, 'admin_roles', type_='foreignkey')
    op.create_foreign_key(op.f('admin_roles_user_id_fkey'), 'admin_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_admin_roles_user_id'), table_name='admin_roles')
    # ### end Alembic commands ###
