"""initial schema: users, services, providers, availability

Revision ID: d33d6f8f5c46
Revises: 
Create Date: 2026-08-17 10:16:26.517515

"""
from typing import Sequence, Union

from alembic import op
import app.models.provider
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33d6f8f5c46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('user_id', app.models.provider.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_area', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cancellation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('no_show_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('on_time_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('response_time_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('availability',
    sa.Column('id', app.models.provider.GUID(), nullable=False),
    sa.Column('provider_id', app.models.provider.GUID(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', app.models.provider.GUID(), nullable=False),
    sa.Column('provider_id', app.models.provider.GUID(), nullable=False),
    sa.Column('document_url', sa.String(length=1024), nullable=False),
    sa.Column('certificate_type', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_by', app.models.provider.GUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_services',
    sa.Column('id', app.models.provider.GUID(), nullable=False),
    sa.Column('provider_id', app.models.provider.GUID(), nullable=False),
    sa.Column('service_id', app.models.provider.GUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_services')
    op.drop_table('certificates')
    op.drop_table('availability')
    op.drop_table('providers')
    # ### end Alembic commands ###

